"""remove ip_addr and offline_timestamp from listens

Revision ID: 0f115f6046d4
Revises: 673f018e0a7b
Create Date: 2026-01-27 22:09:22.283609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f115f6046d4'
down_revision: Union[str, Sequence[str], None] = '673f018e0a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listens', 'ip_addr')
    op.drop_column('listens', 'offline_timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listens', sa.Column('offline_timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('listens', sa.Column('ip_addr', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
