"""add settings table

Revision ID: 15267e6ffbf3
Revises: dd300ab516e3
Create Date: 2026-01-21 21:39:36.361082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15267e6ffbf3'
down_revision: Union[str, Sequence[str], None] = 'dd300ab516e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('value', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('default_value', sa.String(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    # ### end Alembic commands ###
    
    # Insert default settings
    from sqlalchemy import table, column, String, Integer
    from sqlalchemy.sql import insert
    
    settings_table = table('settings',
        column('key', String),
        column('value', String),
        column('type', String),
        column('description', String),
        column('default_value', String)
    )
    
    op.bulk_insert(settings_table, [
        {
            'key': 'ingest_interval_minutes',
            'value': '5',
            'type': 'number',
            'description': 'Minutes between data ingestion',
            'default_value': '5'
        },
        {
            'key': 'app_timezone',
            'value': 'Europe/Berlin',
            'type': 'timezone',
            'description': 'Application timezone (IANA format)',
            'default_value': 'UTC'
        }
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
