"""add_import_job_and_extend_listens

Revision ID: 673f018e0a7b
Revises: 9dfa99d88df4
Create Date: 2026-01-22 11:53:52.919935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '673f018e0a7b'
down_revision: Union[str, Sequence[str], None] = '9dfa99d88df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('imported_records', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_file_hash'), 'import_jobs', ['file_hash'], unique=False)
    op.create_index(op.f('ix_import_jobs_id'), 'import_jobs', ['id'], unique=False)
    op.add_column('listens', sa.Column('import_job_id', sa.Integer(), nullable=True))
    op.add_column('listens', sa.Column('ms_played', sa.Integer(), nullable=True))
    op.add_column('listens', sa.Column('skipped', sa.Boolean(), nullable=True))
    op.add_column('listens', sa.Column('offline', sa.Boolean(), nullable=True))
    op.add_column('listens', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('listens', sa.Column('conn_country', sa.String(), nullable=True))
    op.add_column('listens', sa.Column('ip_addr', sa.String(), nullable=True))
    op.add_column('listens', sa.Column('incognito_mode', sa.Boolean(), nullable=True))
    op.add_column('listens', sa.Column('offline_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_listens_import_job_id'), 'listens', ['import_job_id'], unique=False)
    op.create_foreign_key('fk_listens_import_job_id_import_jobs', 'listens', 'import_jobs', ['import_job_id'], ['id'], ondelete='CASCADE')
    op.alter_column('spotify_tokens', 'token_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spotify_tokens', 'token_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('fk_listens_import_job_id_import_jobs', 'listens', type_='foreignkey')
    op.drop_index(op.f('ix_listens_import_job_id'), table_name='listens')
    op.drop_column('listens', 'offline_timestamp')
    op.drop_column('listens', 'incognito_mode')
    op.drop_column('listens', 'ip_addr')
    op.drop_column('listens', 'conn_country')
    op.drop_column('listens', 'platform')
    op.drop_column('listens', 'offline')
    op.drop_column('listens', 'skipped')
    op.drop_column('listens', 'ms_played')
    op.drop_column('listens', 'import_job_id')
    op.drop_index(op.f('ix_import_jobs_id'), table_name='import_jobs')
    op.drop_index(op.f('ix_import_jobs_file_hash'), table_name='import_jobs')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
