"""initial schema

Revision ID: dd300ab516e3
Revises: 
Create Date: 2026-01-15 15:12:57.188417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd300ab516e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('release_date_precision', sa.String(), nullable=True),
    sa.Column('album_type', sa.String(), nullable=True),
    sa.Column('total_tracks', sa.Integer(), nullable=False),
    sa.Column('image_url_small', sa.String(), nullable=True),
    sa.Column('image_url_medium', sa.String(), nullable=True),
    sa.Column('image_url_large', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('album_id'),
    sa.UniqueConstraint('spotify_id')
    )
    op.create_index(op.f('ix_albums_album_id'), 'albums', ['album_id'], unique=False)
    op.create_table('artists',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image_url_small', sa.String(), nullable=True),
    sa.Column('image_url_medium', sa.String(), nullable=True),
    sa.Column('image_url_large', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('artist_id'),
    sa.UniqueConstraint('spotify_id')
    )
    op.create_index(op.f('ix_artists_artist_id'), 'artists', ['artist_id'], unique=False)
    op.create_table('spotify_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spotify_tokens_id'), 'spotify_tokens', ['id'], unique=False)
    op.create_table('tracks',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('spotify_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('image_url_small', sa.String(), nullable=True),
    sa.Column('image_url_medium', sa.String(), nullable=True),
    sa.Column('image_url_large', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('track_id'),
    sa.UniqueConstraint('spotify_id')
    )
    op.create_index(op.f('ix_tracks_track_id'), 'tracks', ['track_id'], unique=False)
    op.create_table('album_artists',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.PrimaryKeyConstraint('album_id', 'artist_id')
    )
    op.create_table('listens',
    sa.Column('listen_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('context_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ),
    sa.PrimaryKeyConstraint('listen_id'),
    sa.UniqueConstraint('track_id', 'played_at', name='uq_listen_track_played_at')
    )
    op.create_index(op.f('ix_listens_listen_id'), 'listens', ['listen_id'], unique=False)
    op.create_table('track_album',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ),
    sa.PrimaryKeyConstraint('track_id', 'album_id')
    )
    op.create_table('track_artists',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.track_id'], ),
    sa.PrimaryKeyConstraint('track_id', 'artist_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track_artists')
    op.drop_table('track_album')
    op.drop_index(op.f('ix_listens_listen_id'), table_name='listens')
    op.drop_table('listens')
    op.drop_table('album_artists')
    op.drop_index(op.f('ix_tracks_track_id'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_spotify_tokens_id'), table_name='spotify_tokens')
    op.drop_table('spotify_tokens')
    op.drop_index(op.f('ix_artists_artist_id'), table_name='artists')
    op.drop_table('artists')
    op.drop_index(op.f('ix_albums_album_id'), table_name='albums')
    op.drop_table('albums')
    # ### end Alembic commands ###
