"""initial schema

Revision ID: fc338e9f3873
Revises: 
Create Date: 2026-01-10 15:27:55.956605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc338e9f3873'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('image_url_small', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('image_url_medium', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('image_url_large', sa.String(), nullable=True))
    op.drop_column('artists', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'image_url_large')
    op.drop_column('artists', 'image_url_medium')
    op.drop_column('artists', 'image_url_small')
    # ### end Alembic commands ###
